import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Experiment 02 - Crafted.is",
    description: "Generated by create next app",
};

const Layout = ({
    children,
}: {
    children: React.ReactNode
}) => {
    return <section>{children}</section>
}

export default Layout