import React from 'react'
import type { Metadata } from "next";

import {
    SidebarInset,
    SidebarProvider,
    SidebarTrigger,
} from "@/components/ui/sidebar";
import {
    SettingsPanelProvider,
    SettingsPanel,
} from "@/components/settings-panel";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
    title: "Experiment 02 - Crafted.is",
    description: "Generated by create next app",
};

const Layout = ({
    app_sidebar,
    chat
}: {
    app_sidebar: React.ReactNode
    chat: React.ReactNode
}) => {
    return (
        <SidebarProvider>
            {app_sidebar}
            <SidebarInset className="bg-sidebar group/sidebar-inset">
                <header className="dark flex h-16 shrink-0 items-center gap-2 px-4 md:px-6 lg:px-8 bg-sidebar text-sidebar-foreground relative before:absolute before:inset-y-3 before:-left-px before:w-px before:bg-gradient-to-b before:from-white/5 before:via-white/15 before:to-white/5 before:z-50">
                    <SidebarTrigger className="-ms-2" />
                    <div className="flex items-center gap-8 ml-auto">
                        <Button className="gap-0 rounded-full py-0 ps-0">
                            <div className="me-0.5 flex aspect-square h-full p-1.5">
                                <img
                                    className="h-auto w-full rounded-full"
                                    src="https://originui.com/avatar.jpg"
                                    alt="Profile image"
                                    width={24}
                                    height={24}
                                    aria-hidden="true"
                                />
                            </div>
                            @georgelucas
                        </Button>
                    </div>
                </header>
                <SettingsPanelProvider>
                    <div className="flex h-[calc(100svh-4rem)] bg-[hsl(240_5%_92.16%)] md:rounded-s-3xl md:group-peer-data-[state=collapsed]/sidebar-inset:rounded-s-none transition-all ease-in-out duration-300">
                        {chat}
                        <SettingsPanel />
                    </div>
                </SettingsPanelProvider>
            </SidebarInset>
        </SidebarProvider>
    );
}

export default Layout